"""``rs_rich.ext``: the ``rs-rich-ext`` crate from Python (no Rich counterpart).

Everything the port adds on top of Rich: diagnostics and stack traces,
structured data, diffs and test reports, transforms, workflow renderables,
terminal capabilities, inspectors and the extension registry. Each Rust
module is a submodule here (``diagnostic``, ``stacktrace``, ``dashboard``, ``hyperlink``, ``highlighter``, ``event``, ``log_handler``, ``data``, ``transform``);
this package re-exports all of them.
"""

from .._native import (
    Diagnostic,
    Location,
    SourceSnippet,
    Suggestion,
    DiagnosticSpanError,
    StackTrace,
    TraceFrame,
    parse_stacktrace,
    MAX_TRACE_CAUSES,
    DiagnosticsDashboard,
    Hyperlinker,
    FoundLink,
    NumberHighlighter,
    StructuredEvent,
    EventHandler,
    HandledEvent,
    EVENT_KEYWORDS,
    DataNode,
    parse_data,
    detect_format,
    format_for,
    Explorer,
    TableView,
    FlatView,
    flatten,
    unflatten,
    SearchQuery,
    SearchMatch,
    search,
    SearchResults,
    select,
    selector_backends,
    DataChange,
    diff_data,
    DataDiffView,
    Redaction,
    ConfigFileView,
    DataJson,
    Document,
    Select,
    Filter,
    Highlight,
    Redact,
    DataError,
    SelectError,
    DATA_FORMATS,
    SECRET_KEYS,
    Pipeline,
    KeepLines,
    HighlightMatches,
    TransformError,
    PipelineError,
)
from . import diagnostic, stacktrace, dashboard, hyperlink, highlighter, event, log_handler, data, transform  # noqa: E402,F401

__all__ = [
    "Diagnostic",
    "Location",
    "SourceSnippet",
    "Suggestion",
    "DiagnosticSpanError",
    "StackTrace",
    "TraceFrame",
    "parse_stacktrace",
    "MAX_TRACE_CAUSES",
    "DiagnosticsDashboard",
    "Hyperlinker",
    "FoundLink",
    "NumberHighlighter",
    "StructuredEvent",
    "EventHandler",
    "HandledEvent",
    "EVENT_KEYWORDS",
    "DataNode",
    "parse_data",
    "detect_format",
    "format_for",
    "Explorer",
    "TableView",
    "FlatView",
    "flatten",
    "unflatten",
    "SearchQuery",
    "SearchMatch",
    "search",
    "SearchResults",
    "select",
    "selector_backends",
    "DataChange",
    "diff_data",
    "DataDiffView",
    "Redaction",
    "ConfigFileView",
    "DataJson",
    "Document",
    "Select",
    "Filter",
    "Highlight",
    "Redact",
    "DataError",
    "SelectError",
    "DATA_FORMATS",
    "SECRET_KEYS",
    "Pipeline",
    "KeepLines",
    "HighlightMatches",
    "TransformError",
    "PipelineError",
]
