"""``rich.box``: box styles for tables and panels."""

from ._native import (
    ASCII,
    ASCII2,
    ASCII_DOUBLE_HEAD,
    DOUBLE,
    DOUBLE_EDGE,
    HEAVY,
    HEAVY_EDGE,
    HEAVY_HEAD,
    HORIZONTALS,
    MARKDOWN,
    MINIMAL,
    MINIMAL_DOUBLE_HEAD,
    MINIMAL_HEAVY_HEAD,
    ROUNDED,
    SIMPLE,
    SIMPLE_HEAD,
    SIMPLE_HEAVY,
    SQUARE,
    SQUARE_DOUBLE_HEAD,
    Box,
)

__all__ = [
    "Box",
    "ASCII",
    "ASCII2",
    "ASCII_DOUBLE_HEAD",
    "SQUARE",
    "SQUARE_DOUBLE_HEAD",
    "MINIMAL",
    "MINIMAL_HEAVY_HEAD",
    "MINIMAL_DOUBLE_HEAD",
    "SIMPLE",
    "SIMPLE_HEAD",
    "SIMPLE_HEAVY",
    "HORIZONTALS",
    "ROUNDED",
    "HEAVY",
    "HEAVY_EDGE",
    "HEAVY_HEAD",
    "DOUBLE",
    "DOUBLE_EDGE",
    "MARKDOWN",
]
