"""Generate `docs/cli-reference.md` from the binary's own `--help`.

Hand-copied reference is stale the first time somebody renames a flag — the page
this replaces documented 12 of the tool's 30 options and showed `--style` doing
what `--panel-style` now does. Re-run after any CLI change:

    cargo build --release -p rs-rich-cli
    python scripts/gen_cli_reference.py

The prose that cannot be derived from `--help` — defaults, interactions, exit
codes — lives in `docs/cli.md` and is maintained by hand.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXE = ROOT / "target" / "release" / ("rich.exe" if sys.platform == "win32" else "rich")
OUT = ROOT / "docs" / "cli-reference.md"

HEADER = """<!-- GENERATED by scripts/gen_cli_reference.py — do not edit by hand.
     Re-run it after any change to the CLI's arguments. -->

# CLI reference

Every option the `rich` command accepts, taken from the binary's own `--help` so
that this page cannot drift from it.

Looking for how to *do* something rather than what a flag is called? Start at
[Using the CLI](cli.md).

"""

FOOTER = """
## Exit codes

| Code | Meaning |
|------|---------|
| `0` | The resource rendered. With `--diff --threshold`, also: change was within the threshold. |
| `1` | The run failed: the resource could not be read or parsed, a flag was invalid or orphaned, or `--diff --threshold` found more change than allowed. |

`rich` writes diagnostics to stderr and rendered output to stdout, so
`rich --csv data.csv > table.txt` keeps the two apart.

!!! note "A failure always exits non-zero"

    Earlier versions printed a fabricated table and exited `0` when a CSV's
    delimiter could not be determined. That is fixed: unreadable input now fails
    loudly, so `rich --csv "$f" && publish` no longer proceeds on garbage.
"""


def main():
    if not EXE.exists():
        print(f"binary not found at {EXE}; run: cargo build --release -p rs-rich-cli",
              file=sys.stderr)
        return 1

    help_text = subprocess.run(
        [str(EXE), "--help"], capture_output=True, text=True, encoding="utf-8"
    ).stdout.replace("\r\n", "\n")

    # The help is our own artefact with a fixed set of sections. Splitting on
    # those names beats inferring headings: a heading may wrap onto a second
    # line and carry a parenthetical, while the RESOURCE paragraph is prose that
    # merely starts in capitals — an inferring parser read it as a section.
    KNOWN = ["USAGE", "RENDER MODE", "OPTIONS", "ENVIRONMENT"]
    lines = help_text.split("\n")
    sections, order = {}, []
    current, preamble = None, []
    consumed = set()          # line indices that were part of a heading
    i = 1  # line 0 is the banner
    while i < len(lines):
        line = lines[i]
        started = next((k for k in KNOWN if line.startswith(k)), None)
        if started:
            consumed.add(i)
            heading = [line.rstrip()]
            while not heading[-1].rstrip().endswith(":") and i + 1 < len(lines):
                i += 1
                consumed.add(i)
                heading.append(lines[i].rstrip())
            title = " ".join(h.strip() for h in heading).rstrip(":").strip()
            order.append(started)
            sections[started] = {"note": title[len(started):].strip(" ()"), "body": []}
            current = started
        elif current:
            sections[current]["body"].append(line)
        elif line.strip():
            preamble.append(line.rstrip())
        i += 1

    unknown = [l.split(":")[0] for n, l in enumerate(lines)
               if n not in consumed and l.strip() and not l.startswith(" ")
               and l.rstrip().endswith(":")
               and not any(l.startswith(k) for k in KNOWN)]
    if unknown:
        print(f"  warning: unrecognised help section(s): {unknown} — "
              f"add them to KNOWN in this script", file=sys.stderr)

    parts = [HEADER]
    intro = help_text.split("\n", 1)[0].strip()
    parts.append(f"*{intro}*\n")

    titles = {
        "USAGE": "Usage",
        "RESOURCE": "The resource argument",
        "RENDER MODE": "Render modes",
        "OPTIONS": "Options",
        "ENVIRONMENT": "Environment variables",
    }

    for name in order:
        section = sections[name]
        body = "\n".join(section["body"]).strip("\n")
        if not body.strip():
            continue
        parts.append(f"## {titles.get(name, name.title())}\n")
        if section["note"]:
            parts.append(f"{section['note'][0].upper()}{section['note'][1:]}.\n")
        # Left-align the block: the help indents options by four columns, which
        # a code fence would otherwise preserve as dead space.
        dedented = "\n".join(l[4:] if l.startswith("    ") else l
                             for l in body.split("\n"))
        parts.append("```text\n" + dedented.rstrip() + "\n```\n")

    parts.append(FOOTER)
    OUT.write_text("\n".join(parts), encoding="utf-8")

    flags = sorted(set(re.findall(r"--[a-z][a-z-]+", help_text)))
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(flags)} long options)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
