#!/usr/bin/env python3
"""Regenerate crates/rich-interact/src/names.rs from core's tables.

Core keeps its emoji and colour name tables private (they mirror upstream's
`_emoji_codes.py` and `color.ANSI_COLOR_NAMES`), so the pickers in
rs-rich-interact carry the names only and resolve each through core's public
API (`rich::emoji::replace`, `Color::parse`). Run this after a sync changes
either table; `--check` fails when the file is out of date.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "crates" / "rich" / "src"
OUT = ROOT / "crates" / "rich-interact" / "src" / "names.rs"


def names() -> str:
    emoji = re.findall(r'^    \("([^"]+)", "', (CORE / "emoji_codes.rs").read_text(), re.M)
    colors = re.findall(r'^        "([a-z0-9_]+)" => ', (CORE / "color_names.rs").read_text(), re.M)
    lines = [
        "//! Emoji and colour names, from core's tables (generated by",
        "//! `scripts/gen_interact_names.py`; do not edit).",
        "//!",
        "//! Core keeps both tables private, so only the names are here: each is",
        "//! resolved through core's public API, `rich::emoji::replace` and",
        "//! `rich::Color::parse`.",
        "",
        "/// Every emoji shortcode name, sorted.",
        "pub(crate) const EMOJI: &[&str] = &[",
    ]
    lines += [f'    "{name}",' for name in emoji]
    lines += ["];", "", "/// Every colour name, in palette order.", "pub(crate) const COLORS: &[&str] = &["]
    lines += [f'    "{name}",' for name in colors]
    lines += ["];", ""]
    return "\n".join(lines)


def main() -> int:
    text = names()
    if "--check" in sys.argv[1:]:
        if OUT.read_text() != text:
            print(f"{OUT} is out of date; run scripts/gen_interact_names.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
