"""Generate `docs/cli-reference.md` from the binary's own command description.

Hand-copied reference is stale the first time somebody renames a flag — the page
this replaces documented 12 of the tool's 30 options and showed `--style` doing
what `--panel-style` now does. The binary describes itself once (`cli_spec.rs`)
and renders `--help`, `rich docs markdown` and `rich docs config` from that one
description, so this page is those two Markdown outputs, headings shifted down
one level, between the fixed HEADER and FOOTER. Re-run after any CLI change:

    cargo build --release -p rs-rich-cli
    python scripts/gen_cli_reference.py

The prose that cannot be derived from the command description — interactions and
workflows — lives in `docs/cli.md` and is maintained by hand.
"""
import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXE = ROOT / "target" / "release" / ("rich.exe" if sys.platform == "win32" else "rich")
OUT = ROOT / "docs" / "cli-reference.md"

HEADER = """<!-- GENERATED by scripts/gen_cli_reference.py — do not edit by hand.
     Re-run it after any change to the CLI's arguments. -->

# CLI reference

Every option the `rich` command accepts, generated from the same command
description as the binary's own `--help` (`rich docs markdown` and
`rich docs config`) so that this page cannot drift from it.

Looking for how to *do* something rather than what a flag is called? Start at
[Using the CLI](cli.md).

"""

FOOTER = """
`rich` writes diagnostics to stderr and rendered output to stdout, so
`rich --csv data.csv > table.txt` keeps the two apart.

`--report json` writes the result/error envelope to stderr for the same reason:
stdout remains the rendered payload. `rich doctor --report json` is an
informational command: its diagnostic document is written to stdout instead.

Successful reports include `ok`, `code`, `exit_code` and a `result` object.
Failures include the same status fields plus `message` and an `error` object.
The top-level `message` is retained for simple shell consumers; structured
consumers can read `error.message`. Informational exits such as `--help` and
`--version` print their normal text and do not emit a report envelope.

!!! note "A failure always exits non-zero"

    Earlier versions printed a fabricated table and exited `0` when a CSV's
    delimiter could not be determined. That is fixed: unreadable input now fails
    loudly, so `rich --csv "$f" && publish` no longer proceeds on garbage.
"""


def demote(markdown):
    """Shift every heading down one level, leaving fenced code alone, so the
    generated `# rich` sits under this page's `# CLI reference`."""
    out, fenced = [], False
    for line in markdown.split("\n"):
        if line.startswith("```"):
            fenced = not fenced
        elif not fenced and re.match(r"#{1,5} ", line):
            line = "#" + line
        out.append(line)
    return "\n".join(out).strip("\n") + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=pathlib.Path, default=EXE)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not args.binary.exists():
        print(f"binary not found at {args.binary}; run: cargo build --release -p rs-rich-cli",
              file=sys.stderr)
        return 1

    def generated(*command):
        return subprocess.run(
            [str(args.binary.resolve()), "--no-config", *command], capture_output=True,
            text=True, encoding="utf-8", check=True
        ).stdout.replace("\r\n", "\n")

    parts = [HEADER, demote(generated("docs", "markdown")), demote(generated("docs", "config"))]
    parts.append(FOOTER)
    rendered = "\n".join(parts)
    rendered = rendered.replace("\n\n\n", "\n\n")
    if args.check:
        if OUT.read_text(encoding="utf-8") != rendered:
            print("docs/cli-reference.md is stale; regenerate with this binary", file=sys.stderr)
            return 1
        print("docs/cli-reference.md matches the CLI's docs output")
        return 0
    OUT.write_text(rendered, encoding="utf-8")

    flags = sorted(set(re.findall(r"--[a-z][a-z-]+", rendered)))
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(flags)} long options)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
