"""Generate the built-in micro asset gallery: docs/guide/micro/library.md.

Every asset in crates/rich-micro/builtin/ is drawn magnified, a pixel per
square, on the dark background the terminal screenshots use: its still
image as a PNG and, for an animated asset, its animation as a GIF with the
same frame timings. The page's table (between the markers) lists each one
with its alt text, fallbacks, kind and licence, read from its manifest.

    python3 scripts/micro_gallery.py           # rewrite the images and the table
    python3 scripts/micro_gallery.py --check   # fail when either is out of date

The check compares decoded pixels and frame durations, not file bytes, so a
different Pillow version that encodes the same picture differently passes.
Needs Pillow.
"""

from __future__ import annotations

import argparse
import io
import json
from pathlib import Path
import sys

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BUILTIN = ROOT / "crates/rich-micro/builtin"
PAGE = ROOT / "docs/guide/micro/library.md"
MEDIA = ROOT / "docs/media/micro/library"
SCALE = 10
BACKGROUND = (40, 40, 40, 255)  # the screenshots' terminal background, #282828
BEGIN = "<!-- micro-gallery:begin (generated by scripts/micro_gallery.py) -->"
END = "<!-- micro-gallery:end -->"


def assets():
    """Each built-in asset's manifest and directory, in pack order."""
    found = []
    for pack_file in sorted(BUILTIN.glob("*/pack.json")):
        pack = json.loads(pack_file.read_text(encoding="utf-8"))
        for name in pack["packages"]:
            folder = pack_file.parent / name
            found.append((json.loads((folder / "manifest.json").read_text(encoding="utf-8")), folder))
    order = {"status": 0, "dev": 1, "fun": 2}
    return sorted(found, key=lambda item: order.get(item[0]["name"].split("/")[0], 9))


def magnify(frame: Image.Image) -> Image.Image:
    """The frame composited on the background and scaled up, a square per pixel."""
    rgba = frame.convert("RGBA")
    flat = Image.new("RGBA", rgba.size, BACKGROUND)
    flat.alpha_composite(rgba)
    return flat.convert("RGB").resize((rgba.width * SCALE, rgba.height * SCALE), Image.NEAREST)


def frames(path: Path):
    """(frame, duration in ms) for every frame of an animation."""
    image = Image.open(path)
    result = []
    for index in range(getattr(image, "n_frames", 1)):
        image.seek(index)
        result.append((image.copy(), image.info.get("duration", 100)))
    return result


def slug(name: str) -> str:
    return name.replace("/", "-")


def render(manifest, folder):
    """{filename: encoded bytes} for one asset."""
    out = {}
    still = io.BytesIO()
    magnify(Image.open(folder / manifest["static"])).save(still, "PNG", optimize=True)
    out[f"{slug(manifest['name'])}.png"] = still.getvalue()
    if manifest.get("animation"):
        sequence = frames(folder / manifest["animation"])
        pictures = [magnify(frame) for frame, _ in sequence]
        motion = io.BytesIO()
        pictures[0].save(motion, "GIF", save_all=True, append_images=pictures[1:],
                         duration=[ms for _, ms in sequence], loop=0, disposal=1, optimize=False)
        out[f"{slug(manifest['name'])}.gif"] = motion.getvalue()
    return out


def table(found) -> str:
    rows = [
        "| Image | Name | Alt text | Fallback | Kind | Licence |",
        "|---|---|---|---|---|---|",
    ]
    for manifest, folder in found:
        name = manifest["name"]
        image = f"{slug(name)}.gif" if manifest.get("animation") else f"{slug(name)}.png"
        fallback = manifest.get("fallback", {})
        emoji, text = fallback.get("emoji", ""), fallback.get("text", "")
        if manifest.get("animation"):
            sequence = frames(folder / manifest["animation"])
            loop = sum(ms for _, ms in sequence)
            kind = f"animated, {len(sequence)} frames, {loop} ms a loop"
        else:
            kind = "static"
        rows.append(
            f"| ![{manifest['alt']}](../../media/micro/library/{image}){{ width=80 }} "
            f"| `:micro:{name}:` | {manifest['alt']} | {emoji} `{text}` | {kind} "
            f"| {manifest.get('license', '')} |"
        )
    return "\n".join(rows)


def page_with(table_text: str) -> str:
    page = PAGE.read_text(encoding="utf-8")
    start, end = page.index(BEGIN) + len(BEGIN), page.index(END)
    return page[:start] + "\n\n" + table_text + "\n\n" + page[end:]


def decoded(data: bytes):
    """What a viewer shows: each frame's RGB pixels and its duration."""
    image = Image.open(io.BytesIO(data))
    shown = []
    for index in range(getattr(image, "n_frames", 1)):
        image.seek(index)
        shown.append((image.convert("RGB").tobytes(), image.size, image.info.get("duration")))
    return shown


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail when the page or an image is out of date")
    args = parser.parse_args()

    found = assets()
    wanted = {}
    for manifest, folder in found:
        wanted.update(render(manifest, folder))
    page = page_with(table(found))

    if args.check:
        stale = []
        if PAGE.read_text(encoding="utf-8") != page:
            stale.append(str(PAGE.relative_to(ROOT)))
        for filename, data in wanted.items():
            path = MEDIA / filename
            if not path.exists() or decoded(path.read_bytes()) != decoded(data):
                stale.append(str(path.relative_to(ROOT)))
        extra = sorted(p.name for p in MEDIA.glob("*") if p.name not in wanted) if MEDIA.exists() else []
        stale += [str((MEDIA / name).relative_to(ROOT)) for name in extra]
        if stale:
            print("Out of date; run python3 scripts/micro_gallery.py:\n  " + "\n  ".join(stale), file=sys.stderr)
            return 1
        print(f"The micro gallery matches the {len(found)} built-in assets")
        return 0

    MEDIA.mkdir(parents=True, exist_ok=True)
    for path in MEDIA.glob("*"):
        if path.name not in wanted:
            path.unlink()
    for filename, data in wanted.items():
        (MEDIA / filename).write_bytes(data)
    PAGE.write_text(page, encoding="utf-8")
    print(f"Wrote {len(wanted)} images for {len(found)} assets and {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
